baseurl = "https://gotm-model.github.io/"
title = "GOTM"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "General Ocean Turbulence Model"
  copyright = "&copy;2016 GOTM"
  sidebarAbout = [
    "General Ocean Turbulence Model",
    "",
    "GOTM is the result of the effort by a number of people to make 'state-of-the-art' turbulence model for natural waters. Since its inception more than 20 years ago GOTM has grown into a full-fledged 1D water column model with a very extended configuration possibilities including coupling to a collection of bio-geochemical models.",
    "Developed by a group of volunteers over 20+ years.",
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
#  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Blogs"
  url = "blog/"

  [[params.navlinks]]
  name = "History"
  url = "history/"

  [[params.navlinks]]
  name = "Publications"
  url = "publications/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

#  [[params.navlinks]]
#  name = "Contact"
#  url = "contact/"


  [params.social]
#  facebook      = "full page or profile url in facebook"
#  googleplus    = "full profile url in googleplus"
#  email         = "email@example.com"
#  twitter       = "full profile url in twitter"
#  linkedin      = "full profile url in linkedin"
#  stackoverflow = "full profile url in stackoverflow"
#  instagram     = "full profile url in instagram"
  github        = "https://github.com/gotm-model/code"
